"""Generate the small cross-language multiplayer schema tables."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MANIFEST = Path(__file__).with_name("manifest.json")
CPP_OUTPUT = ROOT / "game" / "multiplayer" / "generated" / "multiplayer_schema_generated.h"
GOAL_OUTPUT = ROOT / "goal_src" / "jak2" / "multiplayer" / "core" / "mp-schema-generated.gc"
EVENT_GOAL_OUTPUT = ROOT / "goal_src" / "jak2" / "multiplayer" / "event" / "mp-event-h.gc"

ROLES = {"none": 0, "host_to_client": 1, "both": 3}
PRIORITIES = {"reliable": 0, "bootstrap": 1, "snapshot": 2, "traffic": 3}
RELIABILITY = {"unreliable": 0, "reliable": 1}
COALESCING = {"never": 0, "latest": 1}
CHUNKS = {"replace": 0, "preserve": 1}
CADENCE = {"window": 0, "dirty": 1, "periodic": 2}


def load_manifest() -> dict:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    packets = manifest["packets"]
    if [packet["id"] for packet in packets] != list(range(len(packets))):
        raise ValueError("packet IDs must be contiguous starting at zero")
    for packet in packets:
        if packet["direction"] not in ROLES:
            raise ValueError(f"unknown direction: {packet['direction']}")
        for field, values in (("priority", PRIORITIES), ("reliability", RELIABILITY),
                              ("coalescing", COALESCING), ("chunks", CHUNKS)):
            if packet[field] not in values:
                raise ValueError(f"unknown {field}: {packet[field]}")
    return manifest


def cpp_text(manifest: dict) -> str:
    packet_rows = []
    for packet in manifest["packets"]:
        flags = (RELIABILITY[packet["reliability"]]
                 | (COALESCING[packet["coalescing"]] << 1)
                 | (CHUNKS[packet["chunks"]] << 2))
        cadence = packet.get("cadence", "window")
        if cadence not in CADENCE:
            raise ValueError(f"unknown cadence: {cadence}")
        dirty_only = 1 if packet.get("dirty_only", False) else 0
        packet_rows.append(
            f"    {{{packet['id']}, \"{packet['name']}\", {ROLES[packet['direction']]}, "
            f"{PRIORITIES[packet['priority']]}, {flags}, {packet['max_payload']}, "
            f"{CADENCE[cadence]}, {dirty_only}}},")
    event_rows = [
        f"    {{{event_id}, \"{event['name']}\"}},"
        for event_id, event in enumerate(manifest["events"], start=1)
    ]
    return """// Generated by tools/multiplayer_schema/generate.py. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace multiplayer::schema {

struct PacketDescriptor {
  uint8_t id;
  const char* name;
  uint8_t allowed_roles;
  uint8_t priority;
  uint8_t flags;
  uint16_t max_payload;
  uint8_t cadence;
  uint8_t dirty_only;
};

struct EventDescriptor {
  uint32_t id;
  const char* name;
};

inline constexpr size_t kPacketCount = %d;
inline constexpr size_t kMaxPacketSize = %d;
inline constexpr std::array<PacketDescriptor, kPacketCount> kPackets = {{
%s
}};
inline constexpr std::array<EventDescriptor, %d> kEvents = {{
%s
}};

inline const PacketDescriptor* packet_descriptor(uint8_t id) {
  return id < kPackets.size() ? &kPackets[id] : nullptr;
}

inline const EventDescriptor* event_descriptor(uint32_t id) {
  for (const auto& event : kEvents) {
    if (event.id == id) {
      return &event;
    }
  }
  return nullptr;
}

}  // namespace multiplayer::schema
""" % (len(manifest["packets"]), manifest["max_packet_size"],
       "\n".join(packet_rows), len(manifest["events"]), "\n".join(event_rows))


def goal_text(manifest: dict) -> str:
    lines = [";; Generated by tools/multiplayer_schema/generate.py. Do not edit.",
             "(in-package goal)", ""]
    for packet in manifest["packets"]:
        lines.append(f"(defconstant MP_PACKET_{packet['name']} (the uint {packet['id']}))")
    lines.append("")
    for event_id, event in enumerate(manifest["events"], start=1):
        lines.append(f"(defconstant MP_EVENT_{event['name']} (the uint {event_id}))")
    lines.append("")
    lines.append(f"(defconstant MP_PACKET_COUNT (the uint {len(manifest['packets'])}))")
    lines.append("")
    lines.append("(defun mp-schema-packet-name ((idx int))")
    lines.append("  (cond")
    for packet in manifest["packets"]:
        lines.append(f"    ((= idx {packet['id']}) \"{packet['name']}\")")
    lines.append("    (else \"UNKNOWN\")")
    lines.append("    )")
    lines.append("  )")
    lines.append("")
    lines.append("(defun mp-schema-event-known? ((event-id uint))")
    lines.append("  (cond")
    for event in manifest["events"]:
        lines.append(f"    ((= event-id MP_EVENT_{event['name']}) #t)")
    lines.append("    (else #f)")
    lines.append("    )")
    lines.append("  )")
    return "\n".join(lines)


def event_header_text(manifest: dict) -> str:
    if EVENT_GOAL_OUTPUT.exists():
        current = EVENT_GOAL_OUTPUT.read_text(encoding="utf-8")
    else:
        current = ";;-*-Lisp-*-\n(in-package goal)\n\n"
    begin = ";; BEGIN GENERATED EVENT ALIASES"
    end = ";; END GENERATED EVENT ALIASES"
    if begin in current and end in current:
        before = current.split(begin, 1)[0]
        after = current.split(end, 1)[1]
        return before.rstrip() + after
    return current


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = load_manifest()
    outputs = {
        CPP_OUTPUT: cpp_text(manifest),
        GOAL_OUTPUT: goal_text(manifest),
        EVENT_GOAL_OUTPUT: event_header_text(manifest),
    }
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                print(f"generated schema is out of date: {path}")
                return 1
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
