#pragma once

#include "common/common_types.h"

int pc_multi_get_role();
int pc_multi_set_local_version(u32 version_ptr);
u64 pc_multi_get_local_version();
u64 pc_multi_get_required_version();
void pc_multi_poll(u32 local_ptr, u32 remote_ptr);
int pc_multi_flush_packet_window();
void pc_multi_send_state(u32 local_ptr);
void pc_multi_receive_state(u32 remote_ptr);
void pc_multi_send_events(u32 event_ptr);
void pc_multi_receive_events(u32 event_ptr);
void pc_multi_send_enemies(u32 buffer_ptr);
void pc_multi_receive_enemies(u32 buffer_ptr);
void pc_multi_send_traffic(u32 buffer_ptr);
void pc_multi_receive_traffic(u32 buffer_ptr);
void pc_multi_clear_remote_traffic();
void pc_multi_send_palace_squid(u32 buffer_ptr);
void pc_multi_receive_palace_squid(u32 buffer_ptr);
void pc_multi_send_widow(u32 buffer_ptr);
void pc_multi_receive_widow(u32 buffer_ptr);
void pc_multi_send_airlock_state(u32 buffer_ptr);
void pc_multi_receive_airlock_state(u32 buffer_ptr);
u64 pc_multi_get_enemy_sync_time();
u64 pc_multi_get_vehicle_sync_time(u32 net_id);
void pc_multi_disconnect();
int pc_multi_reconnect();
void pc_multi_setup_host();
void pc_multi_setup_internet_host();
void pc_multi_setup_client(u32 ip_ptr, u32 port);
int64_t pc_multi_get_status();
void pc_multi_set_status(int status);
void pc_multi_request_bootstrap();
// Compatibility export for older GOAL builds; new code uses pc_multi_request_bootstrap.
void pc_multi_request_full_sync();
void pc_multi_stop_search();
void pc_multi_start_search();
u64 pc_multi_get_command_line_arg(u32 str_ptr);
void pc_multi_connect_found_host();
int pc_multi_get_host_invite_status();
int pc_multi_retry_online_setup();
int pc_multi_copy_invite();
int pc_multi_stage_clipboard_invite();
int pc_multi_get_staged_invite_status();
void pc_multi_connect_staged_invite();
void pc_multi_clear_staged_invite();
void pc_multi_clear_direct_connect();
void pc_multi_reset_direct_connect();
u64 pc_multi_get_direct_field(int field);
int pc_multi_edit_direct_field(int field, u32 key);
int pc_multi_direct_connect_ready();
int pc_multi_connect_direct();
void pc_multi_debug_stop_receive(u32 val);
u64 pc_multi_get_ticks();
int pc_multi_get_ping();
int pc_multi_get_packet_loss();
int pc_multi_get_ping_valid();
float pc_multi_get_packet_loss_percent();
float pc_multi_get_packet_loss_variance_percent();
int pc_multi_get_ping_variance();
int pc_multi_get_send_packet_rate();
int pc_multi_get_recv_packet_rate();
u64 pc_multi_get_wire_total_sent_bytes();
u64 pc_multi_get_wire_total_received_bytes();
u64 pc_multi_get_wire_total_sent_packets();
u64 pc_multi_get_wire_total_received_packets();
int pc_multi_get_type_send_rate(int type);
int pc_multi_get_type_recv_rate(int type);
int pc_multi_get_type_total_sent(int type);
int pc_multi_get_type_total_recv(int type);
int pc_multi_get_type_send_packet_rate(int type);
int pc_multi_get_type_recv_packet_rate(int type);
u64 pc_multi_get_type_total_sent_packets(int type);
u64 pc_multi_get_type_total_received_packets(int type);
