#pragma once

#include "common/common_types.h"

int pc_multi_get_role();
u32 pc_multi_get_local_player_id();
u32 pc_multi_get_host_player_id();
u32 pc_multi_get_local_player_character();
int pc_multi_is_lobby_host();
u32 pc_multi_get_session_player_limit();
int pc_multi_lobby_start_game();
int pc_multi_lobby_set_character(u32 character);
int pc_multi_lobby_set_ready(u32 ready);
int pc_multi_lobby_start_countdown(u32 seconds);
int pc_multi_lobby_cancel_countdown();
int64_t pc_multi_lobby_get_countdown_remaining_ms();
int pc_multi_lobby_is_countdown();
u32 pc_multi_get_player_color();
int pc_multi_get_player_appearance(u32 appearance_ptr);
int pc_multi_lobby_set_appearance(u32 appearance_ptr);
void pc_multi_poll(u32 controller_ptr, u32 world_ptr, u32 bootstrap_ptr);
int pc_multi_flush_packet_window();
void pc_multi_send_sync(u32 controller_ptr, u32 world_ptr, u32 bootstrap_ptr);
void pc_multi_receive_sync(u32 controller_ptr, u32 world_ptr, u32 bootstrap_ptr);
void pc_multi_send_events(u32 event_ptr);
void pc_multi_receive_events(u32 event_ptr);
void pc_multi_send_enemies(u32 buffer_ptr);
void pc_multi_receive_enemies(u32 buffer_ptr);
void pc_multi_send_traffic(u32 buffer_ptr);
void pc_multi_receive_traffic(u32 buffer_ptr);
void pc_multi_clear_remote_traffic();
u32 pc_multi_publish_traffic_authority_map(u32 authority_map_ptr);
u32 pc_multi_read_traffic_authority_map(u32 authority_map_ptr);
void pc_multi_set_selected_traffic_authority(u32 selected_authority);
void pc_multi_send_palace_squid(u32 buffer_ptr);
void pc_multi_receive_palace_squid(u32 buffer_ptr);
void pc_multi_send_widow(u32 buffer_ptr);
void pc_multi_receive_widow(u32 buffer_ptr);
void pc_multi_send_airlock_state(u32 buffer_ptr);
void pc_multi_receive_airlock_state(u32 buffer_ptr);
u64 pc_multi_get_enemy_sync_time();
u64 pc_multi_get_vehicle_sync_time(u32 net_id);
void pc_multi_disconnect();
int pc_multi_reconnect();
void pc_multi_setup_host(u32 player_limit, u32 character_config_ptr);
void pc_multi_setup_internet_host(u32 player_limit, u32 character_config_ptr);
void pc_multi_setup_client(u32 ip_ptr, u32 port);
int64_t pc_multi_get_status();
void pc_multi_set_status(int status);
void pc_multi_request_bootstrap();
// Compatibility export for older GOAL builds; new code uses pc_multi_request_bootstrap.
void pc_multi_request_full_sync();
void pc_multi_stop_search();
void pc_multi_start_search();
u64 pc_multi_get_command_line_arg(u32 str_ptr);
void pc_multi_connect_found_host();
int pc_multi_get_host_copy_mode();
int pc_multi_copy_host_access();
int pc_multi_stage_clipboard_invite();
int pc_multi_get_staged_invite_status();
void pc_multi_connect_staged_invite();
void pc_multi_clear_staged_invite();
void pc_multi_clear_direct_connect();
void pc_multi_reset_direct_connect();
u64 pc_multi_get_direct_field(int field);
int pc_multi_edit_direct_field(int field, u32 key);
int pc_multi_direct_connect_ready();
int pc_multi_connect_direct();
u64 pc_multi_get_preference_field(int field);
u64 pc_multi_get_player_name();
int pc_multi_edit_preference_field(int field, u32 key);
int pc_multi_commit_preference_field(int field);
void pc_multi_discard_preference_edits();
int pc_multi_get_automatic_port_mapping();
void pc_multi_set_automatic_port_mapping(int enabled);
void pc_multi_reset_preferences();
u32 pc_multi_get_preference_player_limit();
void pc_multi_set_preference_player_limit(u32 limit);
u32 pc_multi_get_preference_player_character(u32 player_id);
void pc_multi_set_preference_player_character(u32 player_id, u32 character);
int64_t pc_multi_get_host_setup_status();
int pc_multi_get_host_port();
int pc_multi_get_connection_phase();
int pc_multi_get_connection_failure();
void pc_multi_debug_stop_receive(u32 val);
u64 pc_multi_get_ticks();
int pc_multi_get_ping();
int pc_multi_get_packet_loss();
int pc_multi_get_ping_valid();
float pc_multi_get_packet_loss_percent();
float pc_multi_get_packet_loss_variance_percent();
int pc_multi_get_ping_variance();
int pc_multi_get_send_packet_rate();
int pc_multi_get_recv_packet_rate();
u64 pc_multi_get_wire_total_sent_bytes();
u64 pc_multi_get_wire_total_received_bytes();
u64 pc_multi_get_wire_total_sent_packets();
u64 pc_multi_get_wire_total_received_packets();
int pc_multi_get_type_send_rate(int type);
int pc_multi_get_type_recv_rate(int type);
int pc_multi_get_type_total_sent(int type);
int pc_multi_get_type_total_recv(int type);
int pc_multi_get_type_send_packet_rate(int type);
int pc_multi_get_type_recv_packet_rate(int type);
u64 pc_multi_get_type_total_sent_packets(int type);
u64 pc_multi_get_type_total_received_packets(int type);
